### ISSUE TITLE
How do I add a testcase (Request: Documentation on that)

### ISSUE THREAD

**Issue by jeengbe** [moltar/typescript-runtime-type-benchmarks#1012]
```ts
addCase('vality', 'parseSafe', data => {
  const res = validate(dataType, data, { strict: true, bail: true });
  if(res.valid) return res.data;
  throw new Error("Invalid");
});
```
throws an exception on invalid which crashes the process.

```log
Executing "vality"
Loading "vality"
/home/coder/data/typescript-runtime-type-benchmarks/cases/vality.ts:24
  throw new Error('Invalid!');
        ^
Error: Invalid!
    at ParseSafe.fn (/home/coder/data/typescript-runtime-type-benchmarks/cases/vality.ts:24:9)
    at ParseSafe.run (/home/coder/data/typescript-runtime-type-benchmarks/benchmarks/parseSafe.ts:29:10)
```

**Comment by moltar** [comment]
@hoeck Do you have any input on this?

**Comment by hoeck** [comment]
@jeengbe have you tried running the tests with `npm run test` - what do they say?

If a benchmarked library does not implement the benchmark correctly (e.g. raises an exception if the data is valid) the benchmark will crash. The tests are meant to ensure that the benchmarked libraries do indeed conform to the benchmark spec.

**Comment by jeengbe** [comment]
Ah yes, I could debug it with jest. 
That is something that should somewhat be documented 🙈 

Along the lines of
### parseSafe:
- Allows unknown properties
- Throws if invalid
- Returns data if valid

### assertStrict
- Doesn't unknown properties
- Throws if invalid
- Returns true if valid

**Comment by hoeck** [comment]
:+1: also at the bottom of the benchmark graph there is a short description what every benchmark is supposed to test: https://moltar.github.io/typescript-runtime-type-benchmarks/
