### ISSUE TITLE
Add `@Typia`

### ISSUE THREAD

**Issue by moltar** [moltar/typescript-runtime-type-benchmarks#1019]
@samchon Would be nice to see [@Typia](https://github.com/samchon/typia) be benchmarked here
Care to create a test case ?

_Originally posted by @SK-FComputer in https://github.com/moltar/typescript-runtime-type-benchmarks/issues/898#issuecomment-1348104543_

**Comment by FreeNFTj** [comment]
+1

**Comment by SK-FComputer** [comment]
+1

**Comment by moltar** [comment]
Closed via #1023
