### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by sinclairzx81** [moltar/typescript-runtime-type-benchmarks#1062]
Hi @moltar @hoeck !

Hey, would it be possible to include Node 20 in the benchmarks? This was recently released, so would be good to measure for any runtime optimizations they've implemented (either through Node or recent revisions to v8)

Cheers!
S

**Comment by hoeck** [comment]
Hi @sinclairzx81 - of course, thanks for the reminder :grin: I'll create a PR for it.

**Comment by sinclairzx81** [comment]
@hoeck Awesome, thank you :) !
