### ISSUE TITLE
Show operations/s as a number for each benchmark

### ISSUE THREAD

**Issue by dbartholomae** [moltar/typescript-runtime-type-benchmarks#1101]
The bar-graph is hard to read when comparing entries that are not near the best. It would be great to add the numbers as [labels](https://vega.github.io/vega-lite/docs/text.html#labels). If there is interest, I can raise a PR.

**Comment by moltar** [comment]
Hi Daniel 👋

Your suggestion is great. Please make a PR if you have time!

**Comment by dbartholomae** [comment]
Sure! I might not be able to jump on it right away, but I'll add it to my todo list. I expect to be able to get it done over the next few weeks.
Can you point me to an example PR or share insights what I should look out for when contributing?

**Comment by dbartholomae** [comment]
I've opened #1103
