### ISSUE TITLE
[Enchanchament] add Bun runtime in benchmark

### ISSUE THREAD

**Issue by kravetsone** [moltar/typescript-runtime-type-benchmarks#1220]
add [Bun](https://bun.sh/) runtime in benchmark if it possible

It would be useful to compare the results of Bun and NodeJS

**Comment by moltar** [comment]
Great idea. If we can make it work with Bun without any complications, I'd be happy to add it!

**Comment by DarkGL** [comment]
https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1225

**Comment by kravetsone** [comment]
> https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1225

Thanks for the work!
