### ISSUE TITLE
Upgrade to jointz@6.0.1

### ISSUE THREAD

**Issue by moodysalem** [moltar/typescript-runtime-type-benchmarks#224]
I made `isValid` much more performant in 6.0.1, it should be more on par with the other faster libraries. `checkValid` and `validate` both produce errors arrays that cost memory/CPU to construct.

Also, thanks for maintaining this benchmark!

**Comment by moltar** [comment]
Sounds great! Renovate Bot already picked up the changes. I'll manually merge them now, but usually they merge automatically after an hour or so. You should see the results in a few minutes when the GitHub Actions run ends.
