### ISSUE TITLE
SVGs in readme are aggressively cached

### ISSUE THREAD

**Issue by moodysalem** [moltar/typescript-runtime-type-benchmarks#227]
The SVGs in the readme do not reflect the repo due to the cache. Consider updating automation to add a random value to the URLs in the readme after each update.

**Comment by moltar** [comment]
Yeah, caching is pretty annoying. I find the easiest way to bust the cache is to just click on the SVG link to open it directly. That usually refreshes the cache immediately.

Unfortunately adding randomized string to the README would not be that easy, as README is a static file.
