### ISSUE TITLE
Graphs seem to be broken

### ISSUE THREAD

**Issue by hassankhan** [moltar/typescript-runtime-type-benchmarks#298]
None of the graphs on the README seem to have any data on them.

**Comment by moltar** [comment]
Thanks for the report. Seems to be caused by #286. Looking into it.

**Comment by moltar** [comment]
Linking relevant issue: https://github.com/vega/vega/issues/2640

**Comment by shlomiassaf** [comment]
remove SVGO and it will work...

**Comment by moltar** [comment]
@shlomiassaf thanks for the tip. Done!
