### ISSUE TITLE
Add rulr

### ISSUE THREAD

**Issue by moltar** [moltar/typescript-runtime-type-benchmarks#337]
https://github.com/ryansmith94/rulr

Maybe @ryansmith94 can commit a PR? :)

**Comment by ryansmith94** [comment]
@moltar what an awesome repo! Thanks for tagging me, I had no idea this existed. Stunned by the performance of Marshal and Quartet since I hadn't even heard of those packages!

I've added this issue to my notes and I'll try to make a PR soon 👍

**Comment by moltar** [comment]
@ryansmith94 Marshal and Quartet are outliers, because they use jit and/or code gen (eval).

**Comment by ryansmith94** [comment]
That sounds interesting. When you say JIT does that refer to how they're importing different functions? Do you know why they're using eval and why that is faster?

**Comment by moltar** [comment]
It’s basically generating validation code programmatically.

As to why it’s faster I’m not sure. 😁

**Comment by ryansmith94** [comment]
Interesting, sounds like I need to do some research.

**Comment by moltar** [comment]
Also see #300

There’s some useful info there on this topic.

**Comment by ryansmith94** [comment]
Ahhhh thanks for that link, makes perfect sense why their performance is soooo much better. Really interesting.
