### ISSUE TITLE
Add simple-runtypes

### ISSUE THREAD

**Issue by hoeck** [moltar/typescript-runtime-type-benchmarks#377]
Hi, thanks for providing these benchmarks and for collecting all those libraries.

I'd like to add my own runtypes lib to it: https://github.com/hoeck/simple-runtypes - would you accept a PR for that?

**Comment by moltar** [comment]
Yeah, of course!

As long as it fits within the requirements listed in the README, and looks like it does.

**Comment by hoeck** [comment]
Great! 

BTW, having your benchmarks at hand helped me to find some motivation to implement some simple speedups for my module :D.

**Comment by moltar** [comment]
Awesome sauce. Happy to hear people find it useful 😁
