### ISSUE TITLE
TypeScript 4.1 breaking change

### ISSUE THREAD

**Issue by RA80533** [moltar/typescript-runtime-type-benchmarks#506]
Due to [a breaking change](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises) introduced in TypeScript 4.1, `Promise.resolve()` now requires an argument. The most recent builds have been failing due to [an offending line in index.ts](https://github.com/moltar/typescript-runtime-type-benchmarks/blob/4103dc7f1fc4c149cea2fef3e184389ff0db65e2/index.ts#L97) (shown below):

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/4103dc7f1fc4c149cea2fef3e184389ff0db65e2/index.ts#L97

**Comment by moltar** [comment]
Awesome! Thank you for the fix.

I also just added a bunch of fixes to test the actual builds during PR actions to prevent this in the future.

I was only running jest tests, but wasn't running `tsc`.
