### ISSUE TITLE
What about joi library?

### ISSUE THREAD

**Issue by mihanizm56** [moltar/typescript-runtime-type-benchmarks#818]
Hi, we use a lot of validation in browser runtime with "joi" library. Could you please add some benchmarks about this package?

**Comment by moltar** [comment]
Does it fit within the [criteria](https://github.com/moltar/typescript-runtime-type-benchmarks#criteria)?

**Comment by mihanizm56** [comment]
> Does it fit within the [criteria](https://github.com/moltar/typescript-runtime-type-benchmarks#criteria)?

The interface is different, but does the same things. Validate data and give error messages if data is not valid, based on its own schema syntax

**Comment by moltar** [comment]
But does it do type guarding?

**Comment by mihanizm56** [comment]
> But does it do type guarding?

What do you actually mean?

**Comment by moltar** [comment]
Please see docs: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#typeof-type-guards

**Comment by hoeck** [comment]
Looks like Joi does not any type-guarding at all. Also its types are pretty basic when trying to enforce that a schema conforms to an interface:

[typescript playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wFYWHAZlCEOAci2GIG4AoKgYwgDtV5VaALAUxGQEEGBPOAF5M2AHQQARhg60YACgDeVOHggQAXKOBjmUYAwDm8gJQAaKgF8T1KgHo7cBhDgHcHKBwa0OZ1w3coTwATABV+MA5XdAwAV2YUASoYCKi3DxDwyOE4ACUOGFioBiyOAB4UyIhcOFZObj5+MQA3ZAAbYGDkGA4APhoHbThKjnRUDi5hl2aPQTb1cbbBdlkAa2G2bpRale44egDoEHQYF2QGfx6oXGQfKgMrm584ABFu5DhlVVx1LT0DQzUSw0A4JOpcD4iMgSaSyGBlN4wZC9JQqNSabS6GD6IymCzWWygli7ZAASQYrQ6wRy0KkMjkCPeKK+cEkyCgWmhDFiIEkHlMVhsIMYYJJ5MpnQATDTxHS4Yykcy0T8MVyeXyoHjBbYHh4nlEAHKjHrBREfFkqrSKVnsv7YgFwSxA4VMeAMY3GgDKYop7U6Mp0coZRuYHFNTNR31+mP+uPM2qAA)

I am curious to see whether that affects performance, but then adding all the non-ts validation packages would probably make the benchmark results unreadable.

**Comment by moltar** [comment]
I don't think there is room for non-TS packages as there is just way too much prior art and I am not really particularly interested in anything non-TS anyways :)

I'm going to close this issue then.

**Comment by mihanizm56** [comment]
> Looks like Joi does not any type-guarding at all. Also its types are pretty basic when trying to enforce that a schema conforms to an interface:
> 
> [typescript playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wFYWHAZlCEOAci2GIG4AoKgYwgDtV5VaALAUxGQEEGBPOAF5M2AHQQARhg60YACgDeVOHggQAXKOBjmUYAwDm8gJQAaKgF8T1KgHo7cBhDgHcHKBwa0OZ1w3coTwATABV+MA5XdAwAV2YUASoYCKi3DxDwyOE4ACUOGFioBiyOAB4UyIhcOFZObj5+MQA3ZAAbYGDkGA4APhoHbThKjnRUDi5hl2aPQTb1cbbBdlkAa2G2bpRale44egDoEHQYF2QGfx6oXGQfKgMrm584ABFu5DhlVVx1LT0DQzUSw0A4JOpcD4iMgSaSyGBlN4wZC9JQqNSabS6GD6IymCzWWygli7ZAASQYrQ6wRy0KkMjkCPeKK+cEkyCgWmhDFiIEkHlMVhsIMYYJJ5MpnQATDTxHS4Yykcy0T8MVyeXyoHjBbYHh4nlEAHKjHrBREfFkqrSKVnsv7YgFwSxA4VMeAMY3GgDKYop7U6Mp0coZRuYHFNTNR31+mP+uPM2qAA)
> 
> I am curious to see whether that affects performance, but then adding all the non-ts validation packages would probably make the benchmark results unreadable.

TS does not affects benchmarks at all because of building tools.

**Comment by hoeck** [comment]
> TS does not affects benchmarks at all because of building tools.

You're right, but TS validators require a certain style of functional API for the type-inference to work. Maybe that influences performance in comparison to validators that are free to choose whatever API is the most performant, who knows.
