### ISSUE TITLE
What about adding much more test cases?

### ISSUE THREAD

**Issue by samchon** [moltar/typescript-runtime-type-benchmarks#900]
https://github.com/samchon/typescript-json/tree/master/test/structures

I'm developing a runtime type checker (validator) library, and have prepared lots of test cases, for hardcore validation.

How about `typescript-runtime-type-benchmarks` to adapt such test cases? 

They may be useful.

**Comment by samchon** [comment]
If you want to see use-case for benchmark:

https://github.com/samchon/typescript-json/blob/master/benchmark/features/benchmark_is.ts

**Comment by jviide** [comment]
Validation failures are also one less benchmarked case. Their performance also becomes relevant in cases like `union`/`oneOf`/... where some subvalidators might fail while the whole validation succeeds as a whole.
