### ISSUE TITLE
Fix runner script to be cross-platform

### ISSUE THREAD

**Issue by moltar** [moltar/typescript-runtime-type-benchmarks#903]
Ref: https://github.com/moltar/typescript-runtime-type-benchmarks/issues/897#issuecomment-1179449616

**Comment by moltar** [comment]
I'm not sure, tbh. It's an old issue; the context got evicted from my brain. 😂

**Comment by DarkGL** [comment]
I have investigated it, `npm run start` doesn't work on windows, it throws an error,

Putting `node` here:

```const cmd = ['node', ...process.argv.slice(0, 2), 'run-internal', c];```

in `index.ts`

But as we support `bun` now and maybe `deno` in the feature this is not the correct fix
