### ISSUE TITLE
Benchmark is not fair for packages that return a new object

### ISSUE THREAD

**Issue by micnic** [moltar/typescript-runtime-type-benchmarks#929]
It seems that there is a huge gap between the results of different packages in this benchmark, by going deeply in the implementation of the parsing process of packages that perform better I saw that for example `@badrap/valita` does not return a new object and does not strip properties that are not part of the schema, this gives an advantage of about 4 times in some tests that I made with my own package.

It seems that more mature packages do return a new object with the properties copied from the provided object by default, while newer packages tend to return the same value that is provided, which give them some advantage.

I propose to add a criteria for the benchmark results to expect the same object or a new one, this way the unfairness of the results will be minimal.

**Comment by hoeck** [comment]
There are already 4 separate benchmarks (all on the same data though) that try to take these behaviors into account.

What you describe is covered in the "Safe Parsing" benchmark: the package must remove additional properties which are not defined in the schema.
But only the happy case where no additional keys are present is benchmarked. Packages that efficiently detect that the input object does not contain extra keys will have a performance advantage over packages that always copy the object.

Each package runs through a test to ensure it conforms to the benchmarked behavior. For example [this](https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/benchmarks/parseSafe.ts#L38) checks that additional keys are stripped.

So maybe you just looked at the wrong benchmark (assertLoose?).

**Comment by hoeck** [comment]
But in principle I agree that there is a ton of stuff that could be added to make comparisons more fair. Like an indicator whether a package requires eval, the number of dependencies or whether a preprocessing step is necessary.

In addition, more benchmark cases could be added, e.g. to determine performance when parsing tagged unions, intersection types, constructing errors. That all takes quite a lot of time and I have a feeling that it won't change the big picture significantly.

**Comment by micnic** [comment]
Let me be more explicit:
I tried to compare two very similar from the API point of view packages: Valita (performs better in the benchmark) and Zod (performs worse in the benchmark)

I modified the `valita` case to the following:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1449826/180210027-75458564-846a-4e69-9cda-734e32b9383b.png">

I added a check just to see if the result of the parsing is the same object or is a new one, I did the same for `zod` (no screenshot, but trust me :D ).

While running the benchmark in the case of `valita` I do NOT have any log with "new object", but for `zod` there are plenty of them (except for the case when `.passthrough()` method is called).

Like this it seems that the benchmark is checking the parsing process speed in the case of `valita` and it checks the parsing process speed + the speed at which the new object is created in the case of `zod`.

**Comment by hoeck** [comment]
You're right and in my opinion this behavior is totally fine.

Why should Valita return a new object when the original object does not contain any properties that need to be stripped? Valita contains some logic to detect when to return a new vs when to return the same object - again IMO an important performance hack to make.
I see that a lot of real world data seldomly contains additional properties not defined in the schema. Typically only in top levels header structures. Deep down in e.g. long lists of `{x: number, y: number, z: number}` points, you can get massive speedups by not duplicating all these objects during the runtype check.

We could of course add benchmarks that test the performance of stripping keys from an object (which would force every package that implements this to either return a clean new object or delete properties from the parsed object).

Also note that only in the `parseSafe` benchmark stripping of keys is required. In `assertLoose` additional keys are ignored, in `assertStrict` and `parseStrict` its okay to just raise an exception.

**Comment by micnic** [comment]
Ok, thanks for the explanation @hoeck , I will try to improve my package based on this knowledge and get it better at this benchmark.

Feel free to close this discussion.
